In [2]:
import pandas as pd
import openpyxl
import matplotlib.pyplot as plt
from scipy import stats
# !pip install pandas
# !pip install openpyxl

In [8]:
 df.describe()

,heart_rate_bpm,steps,sleeping,spo2_pct,calories_burned,hour,day_of_week,is_weekend,is_anomaly
count,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000,17280.000000
mean,78.563397,77.309491,0.291667,97.435891,6.915233,11.500000,2.900000,0.266667,0.035069
std,18.682703,76.637391,0.454543,0.846274,3.357886,6.922387,1.989195,0.442229,0.183961
min,33.300000,0.000000,0.000000,88.000000,1.010000,0.000000,0.000000,0.000000,0.000000
25%,60.600000,0.000000,0.000000,97.200000,3.500000,5.750000,1.000000,0.000000,0.000000
50%,80.200000,52.000000,0.000000,97.500000,6.600000,11.500000,3.000000,0.000000,0.000000
75%,90.600000,146.000000,1.000000,97.800000,9.900000,17.250000,5.000000,1.000000,0.000000
max,163.600000,592.000000,1.000000,99.400000,15.450000,23.000000,6.000000,1.000000,1.000000

In [4]:
df=pd.read_csv("fitness_data_raw.csv")
print(df)

                 timestamp  heart_rate_bpm  steps  sleeping  spo2_pct  \
0      2024-01-01 00:00:00            62.3      0         1      97.4
1      2024-01-01 00:05:00            65.1      0         1      97.9
2      2024-01-01 00:10:00            58.1      0         1      96.5
3      2024-01-01 00:15:00            54.0      0         1      96.8
4      2024-01-01 00:20:00            56.4      0         1      97.6
...                    ...             ...    ...       ...       ...
17275  2024-02-29 23:35:00            55.6      0         1      97.5
17276  2024-02-29 23:40:00            63.0      0         1      97.8
17277  2024-02-29 23:45:00            58.0      0         1      96.7
17278  2024-02-29 23:50:00            57.0      0         1      96.7
17279  2024-02-29 23:55:00            51.4      0         1      97.7

       calories_burned  hour  day_of_week  is_weekend  is_anomaly anomaly_type
0                 3.32     0            0           0           0       normal
1                 2.98     0            0           0           0       normal
2                 2.09     0            0           0           0       normal
3                 3.45     0            0           0           0       normal
4                 2.22     0            0           0           0       normal
...                ...   ...          ...         ...         ...          ...
17275             3.18    23            3           0           0       normal
17276             3.43    23            3           0           0       normal
17277             3.09    23            3           0           0       normal
17278             3.06    23            3           0           0       normal
17279             2.97    23            3           0           0       normal

[17280 rows x 11 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17280 entries, 0 to 17279
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        17280 non-null  object
 1   heart_rate_bpm   17280 non-null  float64
 2   steps            17280 non-null  int64
 3   sleeping         17280 non-null  int64
 4   spo2_pct         17280 non-null  float64
 5   calories_burned  17280 non-null  float64
 6   hour             17280 non-null  int64
 7   day_of_week      17280 non-null  int64
 8   is_weekend       17280 non-null  int64
 9   is_anomaly       17280 non-null  int64
 10  anomaly_type     17280 non-null  object
dtypes: float64(3), int64(6), object(2)
memory usage: 1.5+ MB

In [9]:
df.isna().sum()

timestamp          0
heart_rate_bpm     0
steps              0
sleeping           0
spo2_pct           0
calories_burned    0
hour               0
day_of_week        0
is_weekend         0
is_anomaly         0
anomaly_type       0
dtype: int64

In [10]:
df.head(4)

,timestamp,heart_rate_bpm,steps,sleeping,spo2_pct,calories_burned,hour,day_of_week,is_weekend,is_anomaly,anomaly_type
0,2024-01-01 00:00:00,62.3,0,1,97.4,3.32,0,0,0,0,normal
1,2024-01-01 00:05:00,65.1,0,1,97.9,2.98,0,0,0,0,normal
2,2024-01-01 00:10:00,58.1,0,1,96.5,2.09,0,0,0,0,normal
3,2024-01-01 00:15:00,54.0,0,1,96.8,3.45,0,0,0,0,normal

In [14]:
df.tail(5)

,timestamp,heart_rate_bpm,steps,sleeping,spo2_pct,calories_burned,hour,day_of_week,is_weekend,is_anomaly,anomaly_type
17275,2024-02-29 23:35:00,55.6,0,1,97.5,3.18,23,3,0,0,normal
17276,2024-02-29 23:40:00,63.0,0,1,97.8,3.43,23,3,0,0,normal
17277,2024-02-29 23:45:00,58.0,0,1,96.7,3.09,23,3,0,0,normal
17278,2024-02-29 23:50:00,57.0,0,1,96.7,3.06,23,3,0,0,normal
17279,2024-02-29 23:55:00,51.4,0,1,97.7,2.97,23,3,0,0,normal